version: '3'
services:
  janus:
    image: damphat/janus-gateway
    build: ./janus/
    
    command:
      - "/usr/local/bin/janus"
      - "-F"
      - "/usr/local/etc/janus"
      - "--nat-1-1"
      - "${DOCKER_IP}"
    
    #network_mode: host
    ports:
      - "10000-10200:10000-10200/udp"
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "7088:7088"
      - "7089:7089"
    volumes:
     - "./janus/config:/usr/local/etc/janus/"
    restart: always

  web:
    image: nginx:alpine
    #network_mode: host
    ports: 
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST:"${NGINX_HOST:-localhost}"
    volumes:
      - "${NGINX_HTML:-./web/html}:/usr/share/nginx/html"
      - "${NGINX_TEMPLATES:-./web/templates}:/etc/nginx/templates"
      - "${NGINX_CERT:-./cert/localhost.crt}:/etc/ssl/certs/janus.crt"
      - "${NGINX_KEY:-./cert/localhost.key}:/etc/ssl/certs/janus.key"
