version: '3'
services:
  janus:
    image: damphat/janus-gateway
    build: ./janus/
    command:
      - "/opt/janus/bin/janus"    
    network_mode: host
    volumes:
     - "./janus/config:/opt/janus/etc/janus/"
    restart: always

  web:
    image: nginx:alpine
    network_mode: host
    depends_on:
      - janus
    environment:
      - JANUS_HOST=localhost
      - DOMAIN_NAME
    volumes:
      - "${NGINX_HTML:-./web/html}:/usr/share/nginx/html"
      - "${NGINX_TEMPLATES:-./web/templates}:/etc/nginx/templates"
      - "${DOMAIN_CERT:-./cert/localhost.crt}:/etc/ssl/certs/${DOMAIN_NAME}.crt"
      - "${DOMAIN_KEY:-./cert/localhost.key}:/etc/ssl/certs/${DOMAIN_NAME}.key"
    restart: always
