version: '3'
services:
  janus:
    image: damphat/janus-gateway
    build: ./janus/
    # after adding --nat-1-1 it works
    command:
      - "/usr/local/bin/janus"
      - "-F"
      - "/usr/local/etc/janus"
      - "--nat-1-1"
      - "178.128.22.184"
    
    #Enable dòng này là chạy ổn nhất, khi enable sẽ không cần NAT-1-1, không cần map ports nữa
    network_mode: host
    ports:
      - "10000-10200:10000-10200/udp"
      - "10000-10200:10000-10200/tcp"
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    volumes:
     - "./janus/config:/usr/local/etc/janus/"
    restart: always

  web:
    image: nginx:alpine
    network_mode: host
    environment:
      - NGINX_HOST:"${NGINX_HOST:-localhost}"
    volumes:
      - "${NGINX_HTML:-./web/html}:/usr/share/nginx/html"
      - "${NGINX_TEMPLATES:-./web/templates}:/etc/nginx/templates"
      - "${NGINX_CERT:-./cert/localhost.crt}:/etc/ssl/certs/janus.crt"
      - "${NGINX_KEY:-./cert/localhost.key}:/etc/ssl/certs/janus.key"
