version: '3'
services:
  janus:
    image: damphat/janus-gateway
    build: ./janus/
    command:
      - "/opt/janus/bin/janus"
      - "-F"
      - "/opt/janus/etc/janus"
      - "-1"
      - "${DOCKER_IP}"
      - "-r"
      - "${JANUS_RTP_PORTS}"
    ports:
      - "${JANUS_RTP_PORTS}:${JANUS_RTP_PORTS}/udp"
      - "8088:8088"
      - "8188:8188"
      - "7088:7088"
    volumes:
     - "./janus/config:/opt/janus/etc/janus/"
    restart: always

  web:
    image: nginx:alpine
    ports: 
      - "80:80"
      - "443:443"
    depends_on:
      - janus
    environment:
      - JANUS_HOST=janus
      - DOMAIN_NAME
    volumes:
      - "${NGINX_HTML:-./web/html}:/usr/share/nginx/html"
      - "${NGINX_TEMPLATES:-./web/templates}:/etc/nginx/templates"
      - "${DOMAIN_CERT:-./cert/localhost.crt}:/etc/ssl/certs/janus.crt"
      - "${DOMAIN_KEY:-./cert/localhost.key}:/etc/ssl/certs/janus.key"
    restart: always
