version: '3'
services:
  janus:
    image: damphat/janus-gateway
    build: ./janus/
    command:
      - "/usr/local/bin/janus"    
    network_mode: host
    volumes:
     - "./janus/config:/usr/local/etc/janus/"
    restart: always
  web:
    image: nginx:alpine
    network_mode: host
    depends_on: [janus]
    environment:
      - JANUS_HOST=${JANUS_HOST:-localhost}
      - NGINX_HOST=${NGINX_HOST:-localhost}
    volumes:
      - "${NGINX_HTML:-./web/html}:/usr/share/nginx/html"
      - "${NGINX_TEMPLATES:-./web/templates}:/etc/nginx/templates"
      - "${NGINX_CERT:-./cert/localhost.crt}:/etc/ssl/certs/janus.crt"
      - "${NGINX_KEY:-./cert/localhost.key}:/etc/ssl/certs/janus.key"
    restart: always
